### ISSUE TITLE
How do I generate matchs.txt in a data set

### ISSUE THREAD

**Issue by shaocy1999** [abenhamadou/Self-Supervised-Endoscopic-Image-Key-Points-Matching#1]
Dear author, thank you for your wonderful paper. 
I have a question after reading your code. I want to know how to generate matches_001.png_002.png.txt files in the data set you gave. I didn't find the code.
![image](https://github.com/abenhamadou/Self-Supervised-Endoscopic-Image-Key-Points-Matching/assets/114813886/04a2a632-9ff6-4d91-b38c-06278fc0e76a)

**Comment by abenhamadou** [comment]
Hello @shaocy1999 

Thank you for your interest in this work. 

In fact, these files correspond to the ground truth matching key-points from pairs of views. We currently don't have a specific script that automatically generates the matches between two views. However, you can follow these steps to create your own ground truth files.

First, you can utilize a well-known feature detector such as SIFT or Surf to detect key-points and match them between the two views. Keep in mind that this process may result in numerous bad matches, which will require manual filtering. 

Let me know if you need further assistance.

**Comment by shaocy1999** [comment]
收到，感谢您的Email！
